name: iOS starter workflow

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main", "ci" ]
    
env:
  SCHEME: FringePlanner
  PROJECT: FringePlanner.xcodeproj

jobs:
  build:
    name: Build and Test using any available iPhone simulator
    runs-on: macos-14

    steps:
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
        
      - name: List available simulators
        run: xcrun xctrace list devices
        
      - name: Show current version of Xcode
        run: xcodebuild -version
        
      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer
          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Current Location
        run: pwd;ls FringePlanner

      - name: Add fake keys
        run: echo -e "FRINGE_API_KEY = fake\nFRINGE_SECRET_SIGNING_KEY = fake" > FringePlanner/Helper/Keys.xcconfig

      - name: Display fake keys
        run: cat FringePlanner/Helper/Keys.xcconfig

      - name: Run Unit Tests
        env:
          platform: ${{ 'iOS Simulator' }}
        run: |
          # xcrun xctrace returns via stderr, not the expected stdout (see https://developer.apple.com/forums/thread/663959)
          device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
          xcodebuild -scheme "$SCHEME" -project "$PROJECT" -destination "platform=$platform,name=$device" -resultBundlePath TestResults.xcresult -testPlan UnitTestPlan test