name: iOS workflow

on:
  push:
    branches: [ "main", "ci" ]
  pull_request:
    branches: [ "main", "ci" ]
    
permissions:
  checks: write
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: macos-14
    timeout-minutes: 10     # Ensures that if the tests get stuck there will me a timeout to reduce the cost of running this

    steps:
      - name: (Debug) List available Xcode versions
        run: ls /Applications | grep Xcode       

      - name: (Debug) Show current version of Xcode
        run: xcodebuild -version
        
      - name: Set up Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
        
      - name: (Debug) List available simulators
        run: xcrun xctrace list devices

      - name: Checkout code
        uses: actions/checkout@v4

      - name: (Debug) Show current location
        run: pwd;ls FringePlanner

      - name: Add fake keys
        run: echo -e "FRINGE_API_KEY = fake\nFRINGE_SECRET_SIGNING_KEY = fake" > FringePlanner/Helper/Keys.xcconfig

      - name: (Debug) Show fake keys
        run: cat FringePlanner/Helper/Keys.xcconfig

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: SwiftLint Code Quality Analysis
        uses: cirruslabs/swiftlint-action@v1
        with:
          version: latest
        
      - name: Run tests using fastlane
        run: fastlane build_and_run_tests
